version: "3"

services:
  db:
    image: postgres:13.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes: 
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks: 
      - back-tier
      - result-tier
  redis:
    image: redis:alpine
    restart: always
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - back-tier
      - poll-tier
  poll:
    build: './poll'
    restart: on-failure
    links:
      - redis
      - db
    depends_on:
      - redis
    ports: 
      - "5000:80"
    networks: 
      - poll-tier
    environment:
      - REDIS_HOSTNAME=redis
  worker:
    build: './worker'
    restart: always
    depends_on:
      - redis
      - db
    networks: 
      - back-tier
    environment:
      - REDIS_HOSTNAME=redis
      - DB_HOSTNAME=db
  result:
    build: './result'
    restart: on-failure
    ports:
      - "5001:80"
    networks:
      - result-tier
    depends_on:
      - db
    environment:
      - DB_HOSTNAME=db

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: